### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by AhmedSafi97** [CA-G12/AnimeX#30]
Well done guys :clap: you've got loads done and your work is just amazing. 

I have left some comments here https://github.com/CA-G12/AnimeX/pull/29 on your code, I hope you find it helpful and if you have any question please feel free to reach out.

**Comment by abdallah-alshawaf** [comment]
Thank you for your review Ahmed. I loved your points and I agree with them. We'll make sure to do them in our code review tomorrow.
